version: "2"

run:
  timeout: 5m    # Abort if we haven’t finished after five minutes
  tests: true    # Include test files: also analyze *_test.go
  go: '1.24.4'   # Define the Go version limit: pin maximum Go version

linters:
  default: standard    # Use the standard recommended set as a baseline
  
  enable:
    # Required linters
    - errcheck      # Detects ignored errors from function calls; helps catch hidden bugs
    - govet         # Built-in Go analyzer (vet tool) to uncover suspicious constructs
    - staticcheck   # Advanced static analysis covering performance, correctness, and style (includes gosimple and stylecheck)
    - unused        # Identifies unused variables, constants, functions, etc. in the codebase

    # Code quality linters
    - bodyclose     # Ensures HTTP response bodies are properly closed to prevent leaks
    - errorlint     # Enforces proper error wrapping practices (Go 1.13+)
    - gosec         # Performs security checks for common issues like hardcoded credentials or unsafe usage
    - revive        # Fast, extensible linter replacing golint; enforces clean, idiomatic code
    - unconvert     # Flags redundant type conversions that don’t improve readability
    - unparam       # Detects unused function parameters — especially helpful in large APIs
    - whitespace    # Ensures consistent and correct use of whitespace for clean diffs and readability

  # Linter settings
  settings:
    gosec:
      # Check medium level vulnerabilities and above
      severity: "medium"
      confidence: "medium"
      
    revive:
      rules:
        - name: exported
          disabled: false
          arguments:
            - "disableStutteringCheck"
        - name: var-naming
          disabled: false
          arguments:
            - ["ID", "API", "HTTP", "URL", "JSON", "XML", "UUID", "SQL", "TCP", "UDP", "IP", "JSON", "JWT", "OAuth"]

  # Linter exclusions
  exclusions:
    # Generated files analysis mode
    generated: lax
    
    # Exclusions for auto-generated code
    rules:
      # Exclude checks from Protobuf files
      - path: ".*\\.pb\\.go$"
        linters:
          - revive
          - unused
          - gosec
          
      # Exclude checks from test files
      - path: "_test\\.go"
        linters:
          - gosec
          - unparam
          
      # Exclude some standard errors
      - linters: [errcheck]
        text: "Error return value of `(os\\.)?std(out|err)\\..*` is not checked"
        
      - linters: [errcheck]
        text: "Error return value of `fmt\\.Print.*` is not checked"

    # Exclude vendor directories and other generated directories
    paths:
      - vendor
      - .bin
      - gen

formatters:
  enable:
    - gci           # Import sorting
    - gofumpt       # Strict formatting
    
  settings:
    gci:
      # Sections for import sorting
      sections:
        - standard                                        # Standard library
        - default                                         # External dependencies
        - prefix(github.com/your-username/repo-starter)   # Project prefix
      custom-order: true
      
    gofumpt:
      # Additional formatting rules
      extra-rules: true

issues:
  # Maximum number of issues to output
  max-issues-per-linter: 50
  max-same-issues: 3
  uniq-by-line: true

# Output results
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true 