version: '3'

vars:
  # --- Dev Dependencies Versions ---
  AIR_VERSION: 'v1.62.0'
  BUF_VERSION: 'v1.55.1'
  GOOSE_VERSION: 'v3.24.3'
  GOLANGCI_LINT_VERSION: 'v2.2.1'
  LEFTHOOK_VERSION: 'v1.11.16'
  GO_VERSION: '1.24.4'
  
  # --- Application binary name ---
  APP_NAME: service-starter

  # --- Directories ---
  BIN_DIR: '{{.ROOT_DIR}}/.bin'
  TOOLS_DIR: '{{.ROOT_DIR}}/.tools'

tasks:
  install:deps:
    desc: "📦 Install all required dev deps to {{.TOOLS_DIR}}"
    cmds:
      - |
        if [ ! -d {{.TOOLS_DIR}} ]; then
          mkdir -p {{.TOOLS_DIR}}
        fi
      - |
        if [ ! -f {{.TOOLS_DIR}}/air ]; then
          GOBIN={{.TOOLS_DIR}} go install github.com/air-verse/air@{{.AIR_VERSION}}
        fi
      - |
        if [ ! -f {{.TOOLS_DIR}}/lefthook ]; then
          GOBIN={{.TOOLS_DIR}} go install github.com/evilmartians/lefthook@{{.LEFTHOOK_VERSION}}
        fi
      - |
        if [ ! -f {{.TOOLS_DIR}}/buf ]; then
          GOBIN={{.TOOLS_DIR}} go install github.com/bufbuild/buf/cmd/buf@{{.BUF_VERSION}}
        fi
      - |
        if [ ! -f {{.TOOLS_DIR}}/goose ]; then
          GOBIN={{.TOOLS_DIR}} go install github.com/pressly/goose/v3/cmd/goose@{{.GOOSE_VERSION}}
        fi
      - |
        if [ ! -f {{.TOOLS_DIR}}/golangci-lint ]; then
          GOBIN={{.TOOLS_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        fi

  # --- Formatting and linting ---
  lint:fix:
    desc: "🔍 Format Syntax and Code Style"
    deps: [install:deps]
    cmds:
      - '{{.TOOLS_DIR}}/golangci-lint run --fix ./...'

  lint:run:
    desc: "🔍 Linting Code Style"
    deps: [install:deps]
    cmds:
      - '{{.TOOLS_DIR}}/golangci-lint run ./...'

  lint:verify:
    desc: "🔍 Verify Linting Config"
    deps: [install:deps]
    cmds:
      - '{{.TOOLS_DIR}}/golangci-lint config verify'

  dev:build:
    desc: "🛠️ Compile Application"
    cmds:
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} ./cmd

  dev:run:
    desc: "🚀 Run Application"
    deps: [install:deps]
    cmds:
      - '{{.TOOLS_DIR}}/air --build.cmd "go build -o {{.BIN_DIR}}/{{.APP_NAME}} ./cmd" --build.bin "{{.BIN_DIR}}/{{.APP_NAME}}"'

  clean:deps:
    desc: "🗑️ Delete dev deps binaries"
    cmds:
      - rm -rf {{.TOOLS_DIR}}
