name: CI

on:
  push:
  pull_request:

jobs:
  extract-vars:
    name: Extract Variables from Taskfile
    runs-on: ubuntu-latest # GitHub Runner VM image
    outputs:
      go-version: ${{ steps.extract.outputs.GO_VERSION }}
      golangci-lint-version: ${{ steps.extract.outputs.GOLANGCI_LINT_VERSION }}
      modules: ${{ steps.extract.outputs.MODULES }}
      buf-version: ${{ steps.extract.outputs.BUF_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Extract variables from Taskfile
        id: extract
        run: |
          chmod +x .github/scripts/extract-versions.sh
          .github/scripts/extract-versions.sh

  debug-vars:
    name: Debug extracted variables
    needs: extract-vars
    runs-on: ubuntu-latest
    steps:
      - name: Show all extracted variables
        run: |
          echo "=== Extracted Variables ==="
          echo "GO_VERSION: ${{ needs.extract-vars.outputs.go-version }}"
          echo "GOLANGCI_LINT_VERSION: ${{ needs.extract-vars.outputs.golangci-lint-version }}"
          echo "MODULES: ${{ needs.extract-vars.outputs.modules }}"

  # lint:
  #   needs: extract-vars
  #   uses: ./.github/workflows/lint-reusable.yml
  #   with:
  #     modules: ${{ needs.extract-vars.outputs.modules }}
  #     go-version: ${{ needs.extract-vars.outputs.go-version }}
  #     golangci-lint-version: ${{ needs.extract-vars.outputs.golangci-lint-version }}
